services:
  - type: web
    name: socoppe
    env: php
    plan: free
    buildCommand: composer install && php artisan migrate --force
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:sDlEv6q/NRR3lslCBACej1oYuST5neKmpIr7bN9PIBA=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: socoppe
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
