services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: composer install && php artisan migrate --force
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xxxxxx (clé générée avec `php artisan key:generate`)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <host-de-la-bdd>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <nom-de-la-bdd>
      - key: DB_USERNAME
        value: <utilisateur>
      - key: DB_PASSWORD
        value: <mot-de-passe>
